### ISSUE TITLE
--max_stack_depth seems to affect forked processes (-log_multiprocess)

### ISSUE THREAD

**Issue by cobalamin** [gaogaotiantian/viztracer#53] opened 2020-11-23 15:06 UTC
Hi,
first of all thank you for creating this tool, it looks very useful! And it might for once fix `multiprocessing` code being hard to profile for me.

An issue I'm encountering is this:

* It looks like the `--max_stack_depth` setting affects the stack in forked processes (`--log_multiprocess`). Maybe it somehow counts the stack depth of the parent process towards this maximum (?).
* Example: The visual output shows a depth of 3 for a subprocess, but I've set `--max_stack_depth 16`. When I increase it to 17, I get one additional stack level in the forked process, but of course that's only 4, not 17.
* Since `multiprocessing` itself adds a bunch of stack depth that I can't really predict, it's hard to figure out to what I should set my stack depth.
* I don't want to look at the stack in the main process so deeply, perfect for me would be seeing a stack depth of about 10 for both the parent process and the forked processes.

**Comment by gaogaotiantian** [comment] 2020-11-24 01:59
Well, let me try to explain this.

I know that the current display of the processes are not optimal, but I'll try to explain why this happens first, and why I did not make it better.

The reason `--max_stack_depth` "did not" apply to the children process successfully, was because the children process was not displayed correctly. If you take a look at the `multiprocessing` code, when the parent process forks, it does something like

```
        if self.pid == 0:
            try:
                os.close(parent_r)
                os.close(parent_w)
                code = process_obj._bootstrap(parent_sentinel=child_r)
            finally:
                os._exit(code)
```

So, the child process did ```os._exit``` after running all the user code, without properly popping out the call stacks. That means, the child process actually starts at a high stack level(the same as the parent when it's calling `fork`, that's how UNIX `fork` works), it's just VizTracer does not display all the call stacks that it "inherits" from its parent because it does not exit normally. 

`--max_stack_depth` actually works as designed, the problematic part is the UI, which is now showing the full stack. 

However, even though I can fix this by adding all the un-returned functions to the UI, they are not interesting generally, and will make the children processes hard to read. Making `--max_stack_depth` work differently on child processes will be another big black hole that may cause some nasty side effects. 

Therefore, the current situation is a design decision, even though it's not perfect. 

But back to the topic, why do you need a very precise `--max_stack_depth`? That is never the intention of the option. Are you worried about the readability or the file size or recorded length or overhead? Normally it's not a horrible practice to record more information than you need. However, if you do have the need to filter out some signals, maybe try `@ignore_function` if you know from which function you are not interested in anymore. `--ignore_c_function` to ignore all builtin stuff. `ignore_non_file` to ignore import stuff. 

If instead of filtering out stuff, you think an inclusive-list would work better, maybe try `@log_sparse`? 

Please let me know if you have a more specific requirement and you can't meet it with the information I provide.

**Comment by gaogaotiantian** [comment] 2020-11-25 03:28
@cobalamin I'll close this issue for now since I did not hear from you again. If you have more questions, feel free to comment or reopen this issue.

**Comment by cobalamin** [comment] 2020-11-25 09:24
Thank you for the detailed information!

I don't need a very precise `--max_stack_depth`. I did however expect that the stack in each subprocess goes as deep (at maximum) as the max stack depth I'm giving (as a rough guess of what I'm interested in). I understand now that this is probably an issue with stack depth semantics of `fork` itself. But from a human perspective, when I'm saying "please log all subprocesses and use a maximum stack depth of 10", I mean that I want each stack that I'm looking at to

**Comment by cobalamin** [comment] 2020-11-25 09:36
Thank you for the detailed information!

I don't need a very precise --max_stack_depth. I did however expect that the stack in each subprocess goes as deep (at maximum) as the max stack depth I'm giving (as a rough guess of what I'm interested in). I am using the max depth as a rough guess, but the usefulness of such a guess goes out the window for me when the stack depth of the parent process (at the moment of the `fork` call) is added onto the stack depth of the child process.

What I thought I was telling viztracer by `--log_multiprocess --max_stack_depth=10` is for each process to start tracking its own stack depth at 0, and then for all traced events to go a maximum of 10 stack frames deep *from there* at any point. I'm not so interested in the stack frames from the parent process above where a subprocess starts, since I can see these in the parent process's section anyways, from what I understand.

I understand now that this is probably a limitation of `fork()` itself or at least what `fork()` takes stack depth to mean canonically in this context, but to me that is not very useful. Do you think it's in principle possible to change viztracer so that it's aware of the "start stack depth" of each forked process and subtracts that off, so that it fits my expectations? If yes, then I'm glad to have a look at that myself.

Sadly, I can't want to use `@ignore_function` since I don't exactly know which functions I would want to ignore, and thus `@log_sparse` isn't for me either at this point. I can't use `--ignore_c_function` since I really *do* want to look at internal stuff. The only reason I'm using something like `--max_stack_depth` is that if I don't, the file size blows up so badly that Chrome refuses to render anything when I open the HTML report.

**Comment by gaogaotiantian** [comment] 2020-11-25 18:26
Okay let me answer different questions.

1. For multi process report, as it's combining multiple reports, it might be reasonable to set `--tracer_entries` to something less than the default value, so no matter how long you've ran the program, it could be loaded by Chrome.

2. VizTracer is using a circular buffer, for finite programs(finish in a short period of time), limiting `--max_stack_depth` will bring down the total entries and make it easier for your browser to render the report. However, for infinite programs(runs for a really long time), the buffer will be filled anyway. The only difference `--max_stack_depth` will make, is how long(to the latest point) VizTracer can log. If that's the case, then changing `--tracer_entries` might be necessary anyway. 

3. I agree that it would be more intuitive, if all the processes honor the `--max_stack_depth` in a way that the displayed report has the maximum depth on all of them. However, in reality, that's tricky because from the program's view, `--max_stack_depth` is honored, just with the call stacks inherited from the parent process. 

4. I can probably make some heuristics for `multiprocessing` library, since it will always exit at the same level of `fork()` as I can tell. However, if you are forking your own process using `os.fork()` and exit normally, you will see the actual *correct* call stack and the heuristics won't work properly(I mean that's what actually happens anyway).

5. It's not against VizTracer's principle to do something after `fork()`. Actually, I plan to add a customizable callback after fork so the users can do whatever they want in multi-process case. 

6. I can understand if all your child processes are doing the same thing, but is the main process doing the same thing as the child processes? At this point, would it make sense to try to match the child processes with `--max_stack_depth`? So you might be getting a lot from the main process, but all your child processes will be good. I would say it's *lucky* that your main process happen to have similar interesting stack depth as your child processes, otherwise changing the behavior of `--max_stack_depth` won't help anyway. 

I'll work on some prototypes in the following holidays for after fork callback and the potential heuristics for `multiprocessing`. You should hear from me soon :)

**Closed** 2020-11-26 20:49 UTC

**Comment by gaogaotiantian** [comment] 2020-11-26 21:07
@cobalamin I implemented the feature I was talking about and released it as 0.10.4. Could you upgrade the version and check if that matches your needs?

**Comment by cobalamin** [comment] 2021-01-19 16:31
Hi @gaogaotiantian, sorry for the late feedback. Thank you very much for the longer explanation and your quick response! It seems like it works fine (i.e., how I personally would like it to work) now :)

I had to manually patch it into `run_code`, inside viztracer/main.py, since I'm calling viztracer for a command-line Python tool rather than calling anything programmatically in a script. Maybe a wrapper script is required in this case.

Thanks again :)

**Comment by gaogaotiantian** [comment] 2021-01-19 19:54
@cobalamin I believe most of the CLI python tool is a shortcut to the actual python module execution. For example, I ask users for VizTracer to use ``viztracer args``, however they can use it by ``python -m viztracer args``. If your tool can be used as ``python -m your_tool``, then you can just trace it by ``viztracer -m your_tool``.
