### ISSUE TITLE
Run viztracer with a script in a different virtual env

### ISSUE THREAD

**Issue by phiresky** [gaogaotiantian/viztracer#201] opened 2022-02-07 10:04 UTC
I can't find a way (in the documentation) to run viztracer on code that is in a different virtual environment than viztracer.

For example the code is in a conda env or a poetry env or a generic venv or installed via `pipx`.

Is this possible or could it be made possible? The docs say even attaching only works if viztracer is importable from the target code. Maybe viztracer could modify `PYTHONPATH` in order to still be able to run?

**Comment by phiresky** [comment] 2022-02-08 10:09
Thanks for the information. I guess then it would be possible to write a wrapper script that runs viztracer for python from any virtualenv by figuring out the interpreter version and injecting the correct viztracer binaries on demand, but I guess it might not be worth the effort since you can in most cases install it directly in the same virtualenv.

It might be useful to add a bit more about this to the readme because from a quick skimming the requirement of installing in the same env isn't immediately obvious.

Feel free to close this issue.

**Comment by gaogaotiantian** [comment] 2022-02-08 18:07
The problem is with wheels, `viztracer` won't have the required binary for other python versions. One way to do that is install the corresponding version of viztracer on attach, but I don't want to inexplicitly install anything on user's machine. I think if the user wants to use viztracer to attach to a process, it is reasonable for them to install `viztracer` for the process they need to attach to.

I will work on the docs and see if I can make it better. I'll close this issue after that. Feel free to let me know if you have any suggestsions.

**Closed** 2022-02-18 05:22 UTC
