### ISSUE TITLE
Error on OS X Catalina with Python 3.9

### ISSUE THREAD

**Issue by hasii2011** [gaogaotiantian/viztracer#32] opened 2020-11-02 15:04 UTC
crashes at end of trace.  Same result whether I run it as a command line or internally as part of the script

See attached file
[OS-X-Dump.txt](https://github.com/gaogaotiantian/viztracer/files/5475902/OS-X-Dump.txt)

**Comment by gaogaotiantian** [comment] 2020-11-02 17:01
Thanks for the issue. Seems like a memory corruption. 

There are a couple of things that might go wrong in this case. Unfortunately I have not met this issue myself and it would be helpful for me to reproduce this or narrow it down. So could you help me with some extra info? I'll try to list in order of the helpfulness.

* Are you running a multi-thread program? Could you confirm the simple single thread hello world program works?
* Are you running the program on a VM with limited memory? Maybe you could try to change the entry number by passing ```--tracer_entries 100000```
* Are you using pycharm? Have you tried to call ```viztracer``` from the terminal directly?

Is your program very complicated and can not be shared? If it's possible, it would be really helpful to have a minimal program that could cause this issue so I can try to narrow this down.

**Comment by hasii2011** [comment] 2020-11-02 18:12
Here is a small test program.   It does require that you install wxPython

[TestWxOgl.py.zip](https://github.com/gaogaotiantian/viztracer/files/5477069/TestWxOgl.py.zip)

I tried 
--tracer_entries 100000 (same result)
I tried viztracer from the terminal (same result)
I am using it also inside PyCharm

**Comment by gaogaotiantian** [comment] 2020-11-02 20:17
Hi @hasii2011, I've located the bug causing this. I'm working on a fix and the fix will be checked in today.

**Comment by hasii2011** [comment] 2020-11-02 21:15
Thanks for the quick response

**Comment by gaogaotiantian** [comment] 2020-11-03 05:02
Fixed on https://github.com/gaogaotiantian/viztracer/commit/3fc01609a512813cb0994969b3a90cb575b789f0

The fix is included in 0.9.2

This problem happens when a C static method is called and recorded. I did not check ```m_self``` against ```null``` so it's a ```null``` dereference. 
I'm not able to produce this with vanilla python because I can't trigger a C static method. However, I was able to reproduce this bug with wxPython locally and confirmed it was fixed. 

@hasii2011 could you confirm it is fixed on your end as well? And if it is, could you close this issue? Thanks. Hopefully this incident will not drive you away from VizTracer :)

**Comment by hasii2011** [comment] 2020-11-03 12:05
The test program works correctly.  However, my real program that is hosted here:
https://github.com/hasii2011/PyUt

Still segV's

Maybe you can git clone the project to execute it;   It does require a virtual environment.

I am a polling official so will be busy all day today.  Let me know how I can help you with the above.

>viztracer --tracer_entries 100000 Pyut.py CardinalityTest.put


[CardinalityTest.put.zip](https://github.com/gaogaotiantian/viztracer/files/5481064/CardinalityTest.put.zip)

**Comment by gaogaotiantian** [comment] 2020-11-03 18:43
I cloned your project and made some modifications to run it(locale part). I was able to run the test and it stopped at some GUI with some drawings. I closed the project and the log was generated successfully. I was doing it on WSL instead of a Mac though. 

So the first thing I would like you to confirm is that, are you using the updated VizTracer? If you are using virtualenv, it's possible that you are using different versions when you are testing the simple case and the CardinalityTest. Could you run ```pip show viztracer``` and make sure you are using ```0.9.2``` before you run your test? Or try to uninstall the package and install it again.

My major development was done on WSL but the tests run on MacOS using github VM. It would be interesting if this can be only reproduced on MacOS. I have a MacBook and can try to reproduce it when we rule out the simple possibilities. 

If it still fails, could you send me the dump log? Also, if you are familiar with gdb, you can run ```gdb --args viztracer Pyut.py CardinalityTest.put``` and in the interactive shell do ```run```. If it's a memory violation(SegFault), it should be able to tell you the place where it failed.

**Comment by hasii2011** [comment] 2020-11-04 04:35
This is my virtual environment.  Both run in that environment;  Note that I am running a very late wxpython snapshot build

![VirtualEnvVersion](https://user-images.githubusercontent.com/1261602/98066077-8ccb0e00-1e1b-11eb-91f8-8a8b66ff3bfb.png)

**Comment by gaogaotiantian** [comment] 2020-11-04 04:42
There's no wheel for wxPython 4.1.1 and I was not able to build from the source when I tried. Does the wxPython matter for your project and will 4.1.0 stable version work?

If you are using clang(which is the mac default), run ```gdb -- viztracer Pyut.py CardinalityTest.put```. It might be helpful for me to locate the problem with some logs now that I have not been able to reproduce it locally.

**Comment by hasii2011** [comment] 2020-11-04 04:49
wxpython 4.1.0 stable is fine for me;  I have no dependencies on 4.1.1;  I am switching my environment back to the stable version of wxython

**Comment by gaogaotiantian** [comment] 2020-11-04 04:58
Another difference is that I'm using python 3.8 because there's no wheel for 3.9. Still, at this point, I'm not sure what might cause the different behavior between your viztracer and mine. If you could provide more info like dump log or gdb info, that would be great.

**Comment by hasii2011** [comment] 2020-11-04 15:44
Here is a wxpython stable version stack trace from Mac

[Pyut-dump-wxpythonStable.log](https://github.com/gaogaotiantian/viztracer/files/5488828/Pyut-dump-wxpythonStable.log)

I'll switch to my Python 3.8 venv and install viztracer there

**Comment by gaogaotiantian** [comment] 2020-11-04 17:28
I definitely want to track this down on Python 3.9. I will take a close look at 3.9 wheels for wxPython and see if CPython changes something that broke the logic.

However, I'm really glad that it worked out on python 3.8 so you'll at least have something!

**Comment by gaogaotiantian** [comment] 2020-12-08 01:53
Hi @hasii2011 . Now that wxPython has 3.9 wheels, I went back and checked on this issue. I installed wxPython 4.1.1, with python 3.9.0, and pulled the latest changes from your repo. Then I tried the command you mentioned, VizTracer worked fine without any segfaults. 

During the time, VizTracer has upgraded to 0.10.x, and wxPython probably fixed some of the issues on its way to stable 4.1.1. So could you confirm with the latest VizTracer and wxPython stable, you can still reproduce this issue? 

If you still can, then I might need to grab a Mac to figure it out.

**Comment by hasii2011** [comment] 2020-12-08 21:28
Let me work on this

**Comment by gaogaotiantian** [comment] 2020-12-19 19:42
Hi @hasii2011, I never heard from you again. Do you still want me to track this bug? Not sure if you are still using VizTracer or if it works well for you.

**Comment by hasii2011** [comment] 2020-12-19 19:49
You can probably close it.  I am not using VizTracer anymore

**Comment by gaogaotiantian** [comment] 2020-12-19 19:51
Okay, thank you for the feedback!

**Closed by gaogaotiantian** 2020-12-19 19:51 UTC
Labels: help wanted, need further investigation
