### ISSUE TITLE
viztracer crash when tracing a concurrent.futures program

### ISSUE THREAD

**Issue by ogrisel** [gaogaotiantian/viztracer#141] opened 2021-08-18 12:53 UTC
Here is the program to profile:

```python
from concurrent.futures import ProcessPoolExecutor
import time
import random
import os


def my_function(*args):
   pid = os.getpid()
   duration = random.random() * 2
   print(f"[{pid}] sleeping {duration:.3f} s")
   time.sleep(duration)
   print(f"[{pid}] done")



if __name__ == '__main__':
    e = ProcessPoolExecutor(max_workers=4)

    print("[main] start")

    e.map(my_function, range(8))

    print("[main] done")
```

It works fine when executing it with Python directly:
```
❯ python bench_concurrent_futures.py
[main] start
[main] done
[10476] sleeping 1.915 s
[10475] sleeping 0.946 s
[10474] sleeping 1.767 s
[10473] sleeping 0.093 s
[10473] done
[10473] sleeping 1.998 s
[10475] done
[10475] sleeping 1.657 s
[10474] done
[10474] sleeping 0.190 s
[10476] done
[10476] sleeping 1.300 s
[10474] done
[10473] done
[10475] done
[10476] done
```

Here the observed output when tracing it with viztracer:

```
❯ viztracer bench_concurrent_futures.py
[main] start
[main] done
Traceback (most recent call last):
  File "<string>", line 1, in <module>
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/ogrisel/miniforge3/envs/dev/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Users/ogrisel/miniforge3/envs/dev/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/ogrisel/miniforge3/envs/dev/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/Users/ogrisel/miniforge3/envs/dev/lib/python3.9/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
    exitcode = _main(fd, parent_sentinel)
  File "/Users/ogrisel/miniforge3/envs/dev/lib/python3.9/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/Users/ogrisel/miniforge3/envs/dev/lib/python3.9/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
Loading finish                                        
==================================================
== Starting from version 0.13.0, VizTracer will ==
== use json as the default report file. You can ==
== generate HTML report with "-o result.html"   ==
==================================================
Dumping trace data, total entries: 7243
Saving report to /Users/ogrisel/result.json ...
Use "vizviewer <your_report>" to open the report
```

I have also tried with `--log_multiprocess` (since the `concurrent.futures.ProcessPoolExecutor` is based on `multiprocessing` building blocks) but then I get even more non-nonsensical results:

```
❯ viztracer --log_multiprocess bench_concurrent_futures.py
[main] start
[main] done
Loading finish                                        
==================================================
== Starting from version 0.13.0, VizTracer will ==
== use json as the default report file. You can ==
== generate HTML report with "-o result.html"   ==
==================================================
Dumping trace data, total entries: 4591
Saving report to /Users/ogrisel/viztracer_multiprocess_tmp_10621_1629291164/result_10621.json ...
Use "vizviewer <your_report>" to open the report
==================================================
== Starting from version 0.13.0, VizTracer will ==
== use json as the default report file. You can ==
== generate HTML report with "-o result.html"   ==
==================================================
Dumping trace data, total entries: 4591
Saving report to /Users/ogrisel/result.json ...
Use "vizviewer <your_report>" to open the report
Traceback (most recent call last):
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "<string>", line 5, in <module>
  File "/Users/ogrisel/miniforge3/envs/dev/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
  File "/Users/ogrisel/miniforge3/envs/dev/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/ogrisel/code/viztracer/src/viztracer/patch.py", line 141, in _main_3839
    exitcode = _main(fd, parent_sentinel)
  File "/Users/ogrisel/code/viztracer/src/viztracer/patch.py", line 141, in _main_3839
    self = reduction.pickle.load(from_parent)
    self = reduction.pickle.load(from_parent)
  File "/Users/ogrisel/miniforge3/envs/dev/lib/python3.9/multiprocessing/synchronize.py", line 110, in __setstate__
  File "/Users/ogrisel/miniforge3/envs/dev/lib/python3.9/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/Users/ogrisel/miniforge3/envs/dev/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/ogrisel/code/viztracer/src/viztracer/patch.py", line 141, in _main_3839
    self = reduction.pickle.load(from_parent)
  File "/Users/ogrisel/miniforge3/envs/dev/lib/python3.9/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "<string>", line 5, in <module>
  File "/Users/ogrisel/miniforge3/envs/dev/lib/python3.9/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Users/ogrisel/code/viztracer/src/viztracer/patch.py", line 141, in _main_3839
    self = reduction.pickle.load(from_parent)
  File "/Users/ogrisel/miniforge3/envs/dev/lib/python3.9/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory
```

I am running Python 3.9.2 and today's viztracer master.

**Comment by ogrisel** [comment] 2021-08-18 12:59
Note that here, I am using the default start method which is the "fork" start method on macos. I have also tried with the `spawn` start method which is the default on Windows but it fails similarly. Here is the code to change the start method:

```python
import multiprocessing as mp
from concurrent.futures import ProcessPoolExecutor
import time
import random
import os


def my_function(*args):
   pid = os.getpid()
   duration = random.random() * 2
   print(f"[{pid}] sleeping {duration:.3f} s")
   time.sleep(duration)
   print(f"[{pid}] done")



if __name__ == '__main__':
    e = ProcessPoolExecutor(
        max_workers=4,
        mp_context=mp.get_context("spawn"),
    )

    print("[main] start")

    e.map(my_function, range(8))

    print("[main] done")
```


For information, my end goal would be to use viztracer with [loky](https://github.com/joblib/loky) which is an extension for the `concurrent.futures` of the standard library.

**Comment by gaogaotiantian** [comment] 2021-08-18 20:42
Okay so this is a multi-layer problem and let me try to explain it.
1. Starting Python 3.8, ``multiprocessing``'s start method on MacOS defaults on ``spawn`` instead of ``fork``, so the second program you gave is the same as your original one :)
2. I tried to reproduce this issue, and this problem only happens on 3.9. I believe it's because starting 3.9, Python uses an undocumented ``threading`` cleanup to replace the more official ``atexit`` one(for multi-interpreter preparation I think).
3. This specific error only happens on MacOS +``spawn``, I think it's because the main process exits without waiting for the ``ProcessPoolExecutor`` to read everything in. However, MacOS + ``fork`` will have another problem that it halts forever(also presumably because of the exit clean up).
4. The documentation did not mention it specifically, but I do believe the correct way to use ``ProcessPoolExecutor`` is to explicitly release the resource using ``with`` statement or do ``shutdown()`` before the program exits, and that's how the official docs did it. The problem will go away if you explicitly release the resource(in all circumstances).
5. I still do treat this as a bug as people will expect ``viztracer`` to perform just as ``python``, whether they have used the library correctly. I believe I have found a solution and I should be able to check in the fix soon.

Thank you for the issue, let me know if you need anything else!

**Comment by gaogaotiantian** [comment] 2021-08-19 04:58
I checked in the fix(I think) for this issue. If you have some time you could try the master branch to see if the issue persists.

**Closed by gaogaotiantian** 2021-08-19 04:58 UTC
Labels: bug

**Comment by ogrisel** [comment] 2021-08-19 07:46
I agree with your analysis.

**Comment by ogrisel** [comment] 2021-08-19 07:54
I confirm this works as expected on this program. I still have problems with loky though. I will open another report.

**Comment by ogrisel** [comment] 2021-08-19 12:15
And thanks for the quick fix, BTW!
