### ISSUE TITLE
Failed to trace C extension function in  numpy

### ISSUE THREAD

**Issue by chenming6615** [gaogaotiantian/viztracer#154] opened 2021-09-16 16:14 UTC
Hi, first thank you for making this awesome project !

I am trying to trace the execution of numpy with the following code:

``` python
import numpy as np
from viztracer import VizTracer

tracer = VizTracer()
tracer.start()

y=np.add(1, 1)  # np.add is a C extension function
print(y)

tracer.stop()
tracer.save()

```

The output result.json is

``` json
{"traceEvents": [{"ph": "M", "pid": 42431, "tid": 42431, "name": "process_name", "args": {"name": "MainProcess"}}, {"ph": "M", "pid": 42431, "tid": 42431, "name": "thread_name", "args": {"name": "MainThread"}}, {"pid": 42431, "tid": 42431, "ts": 38383897163.672, "dur": 8.496, "name": "builtins.print", "ph": "X", "cat": "FEE"}], "viztracer_metadata": {"version": "0.14.0"}, "file_info": {"files": {}, "functions": {}}}
```
The expected `np.add` event is missing.

How to make such  C extension functions traceable?

**Comment by gaogaotiantian** [comment] 2021-09-16 16:52
I believe this is a ``numpy`` specific issue. I did not dig too much into it but I believe ``numpy`` has some optimization there to prevent the python profile hook from executing. This is not something that can be solved from viztracer side, as ``sys.setprofile`` can't catch the ``numpy.add`` call. I do remember that some of the ``numpy`` functions are traceable.

I'm not a numpy expert, I may spend some time in this in the future, but I'm on vacation now and have limited time working on this. However, anyone is welcome to figure out why ``numpy`` won't trigger the profile hook.

**Comment by chenming6615** [comment] 2021-09-20 04:54
Hi, I investigated this issue by debugging the source code of CPython with GDB. 
Here is the function in ceval.c that CPython decides a function call should whether be traced or not:

``` C
static PyObject *
trace_call_function(PyThreadState *tstate,
                    PyObject *func,
                    PyObject **args, Py_ssize_t nargs,
                    PyObject *kwnames)
{
    PyObject *x;
    if (PyCFunction_Check(func)) {
        C_TRACE(x, _PyObject_Vectorcall(func, args, nargs, kwnames));
        return x;
    }
    else if (Py_TYPE(func) == &PyMethodDescr_Type && nargs > 0) {
        /* We need to create a temporary bound method as argument
           for profiling.

           If nargs == 0, then this cannot work because we have no
           "self". In any case, the call itself would raise
           TypeError (foo needs an argument), so we just skip
           profiling. */
        PyObject *self = args[0];
        func = Py_TYPE(func)->tp_descr_get(func, self, (PyObject*)Py_TYPE(self));
        if (func == NULL) {
            return NULL;
        }
        C_TRACE(x, _PyObject_Vectorcall(func,
                                        args+1, nargs-1,
                                        kwnames));
        Py_DECREF(func);
        return x;
    }
    return _PyObject_Vectorcall(func, args, nargs | PY_VECTORCALL_ARGUMENTS_OFFSET, kwnames);
}
```

The direct cause is that `numpy.ufunc`,  to which the `numpy.add` gets transformed, meets neither the `PyCFunction_Check(func)`  nor the `Py_TYPE(func) == &PyMethodDescr_Type` condition. Thus,  the C_TRACE macro is not get called.

What I haven't figured out yet is that:

1.  How does `numpy.add` get transformed into `numpy.ufunc`?
2.  Why does `numpy.ufunc` meet neither the `PyCFunction_Check(func)`  nor the `Py_TYPE(func) == &PyMethodDescr_Type` condition?
 
Also, I tried to trace `pytorch` and get the same kind of issue.

I think this is important since THE most important usage of python nowadays, IMHO, is deep learning. A tool that can trace the implementations of those complex deep learning frameworks is utterly desired.

Hope we can find a solution for this.  

Thanks!

**Comment by gaogaotiantian** [comment] 2021-09-20 05:18
I agree that this is a very important usage. ``numpy`` probably has some optimization that made the ``add`` function a pure C function, instead of a PyCFunction.

I'm not an expert on CPython implementation, I can understand your investigation but I do not know the root cause of it either.

However, I do know pretty well about viztracer's mechanism. VizTracer relies on the CPython hook function, to be more specific, ``PyEval_SetProfile``. If the function to be traced does not trigger this callback function, there's really not much viztracer can do about it. This would be a ``numpy`` design choice, or a CPython issue.

From another point of view, a ML/DL engineer, even with the fact that they are working heavily with the ML framework, may not need to trace every single fundamental call, especially for profiling, maybe for debugging too. They might get enough information from the traceable call stack. For example, I know sklearn is using viztracer for profiling and they get something pretty useful from it.

So for this issue, I have two proposals:
1. Maybe digging into the root cause of not able to trace ``numpy`` functions, and see how could ``numpy`` or CPython could solve it(and are they willing to do so)
2. Try ``viztracer`` in a real ML problem and see if the basic functions are critical to trace to get enough useful information.

**Comment by gaogaotiantian** [comment] 2023-10-06 17:30
Well, C extensions are supported - C functions are not. Basically if you call into a C extension from Python code, it will be recorded. VizTracer is not able to log all the C calls. In short, anything logged by `sys.setprofile` will be logged by VizTracer.

py-spy can log C-level functions, yes. perf is designed for C-level functions so it will work too (the Python-level support is not as good).

However, both py-spy and perf are sampling profilers, not tracers. So if you need profiling, they are great tools, but they can do what VizTracer does.

**Comment by gaogaotiantian** [comment] 2024-11-10 02:34
So basically, viztracer (and Python) can only trace `PyCFunction`, which ufunc of numpy is not. At this point, there's nothing we can do to make it work, so I'll close this for now.

**Closed by gaogaotiantian** 2024-11-10 02:34 UTC
Labels: help wanted, need further investigation
